### ISSUE TITLE
Is there a way to relaunch tests with a failed seed in PHPUnit?

### ISSUE THREAD

**Issue by devnix** [Innmind/Immutable#14]

**Comment by Baptouuuu** [comment]
Hi, not it's not possible but you should have the generated data printed out to the console (I suppose you're talking about a BlackBox test?!).

Did you find a failing scenario ?

**Comment by devnix** [comment]
Yes, well, while I was testing the library with a basic addition implementation I hit an edge case of PHP with a type error, and the output did not show anything. Let me create a reproducer!

**Comment by Baptouuuu** [comment]
Released in `innmind/black-box:5.2.0` the data generated that resulted in an error are now printed as well

<img width="855" alt="Screenshot 2023-08-19 at 11 31 14" src="https://github.com/Innmind/Immutable/assets/851425/39e16319-e063-4e32-ad48-114de6eae8f9">

**Comment by devnix** [comment]
Thank you so much for taking a look into this! ❤️
